tasks:
  - name: Docker-compose
    command: cd Docker && docker-compose up -d && sleep 30 && gp sync-done prev

  - name: Nats-receive
    command: gp sync-await prev && docker exec -it client1 python /home/natscode/receive.py -s nats subject=demo && gp sync-done prev1
    openMode: split-right
 
  - name: Nats-send
    command:  sleep 10 && docker exec -it client2 /bin/bash -c 'python /home/natscode/send.py -s nats subject=demo -d "test"'
    openMode: split-right
